export declare const genGranicusDate: (date: any) => string;
export declare const genDateFromDateMinusDays: (user_date: any, days_ago: any) => string;
export declare const getDaysDiffFromDates: (early_date: any, late_date: any) => number;
export declare const firstEmailDate: Date;
export declare const heavy_date = "March 30, 2020";
export declare const medium_date = "March 12, 2019";
export declare const light_date = "March 1, 2010";
export declare const first_days_ago: number;
export declare const light_days_ago: number;
export declare const medium_days_ago: number;
export declare const heavy_days_ago: number;
